# -*- coding: utf-8 -*-
"""Final Project - Stephanie Franco.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16ynxAEYDgvcBerosvQY1NeQ6OnBKBObj

**TEST FOR CANIDIAN CITIZENSHIP**
"""

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import cv2
import time

class color:
  PURPLE = '\033[95m'
  CYAN = '\033[96m'
  DARKCYAN = '\033[36m'
  BLUE = '\033[94m'
  GREEN = '\033[92m'
  YELLOW = '\033[93m'
  RED = '\033[91m'
  BOLD = '\033[1m'
  UNDERLINE = '\033[4m'
  ITALICS = '\033[3m'
  END = '\033[0m'


print(color.BLUE +"________________________________________________"+color.END)
print(color.BOLD + color.UNDERLINE+ color.BLUE + "WELCOME TO THE TEST FOR THE CANADIAN CITIZENSHIP\n"+color.END)


print(color.ITALICS + "\nThe following information will be used for interal purposes\n"+color.END)


while True:
    name = input("\nPlease enter your name: ")
    if name.isalpha():
        break
    else:
        print("\nInvalid input. Enter letters only")


while True: 
    phone=input('\nPlease enter your phone number:')
    if phone.isnumeric():
        break 
    else:
      print(("\nInvalid input. Enter numbers only"))


input("\nPlease enter your Email: ")


print(color.ITALICS + "\nBefore you start the quizz, please select how many seconds do you need before you start the test.")
print("During this time make sure you are in a quiet space, get water if necessary as well as a notebook and pencil for any notes."+color.END)
print(color.BLUE + "\n*********************************"+ color.END)
print("1 minute = 60 seconds \n30 minutes= 1800 seconds \n60 minutes(1 hour) = 3600 seconds ")
print(color.BLUE + "**********************************"+ color.END)


def countdown():
 user_input = int(input("Enter the time in seconds: "))
 while user_input:
   minutes, seconds = divmod(user_input, 60)
   print( '{:02d}:{:02d}'. format(minutes, seconds), end = '\r')
   time.sleep(1)
   user_input -= 1


 print(color.BOLD + "The countdown is done! Please start the test" + color.END)

countdown()



def new_game():


   guesses = []
   correct_guesses = 0
   question_num = 1
   counter=1


   for key in questions:
       print(" ")
       print(color.BOLD + "Question",counter,"of 20\n"+ color.END)
       counter += 1
       print(key)
       for i in options[question_num-1]:
           print(i)
       guess = input("\nEnter (A, B, C, or D): ")
       guess = guess.upper()
       guesses.append(guess)


       correct_guesses += check_answer(questions.get(key), guess)
       question_num += 1


   display_score(correct_guesses, guesses)



def check_answer(answer, guess):


   if answer == guess:
       print(color.GREEN+"\nCongrats! Your answer is Correct"+ color.END)
       return 1
   else:
       print(color.RED+ "\nSorry! Try next time, your answer is wrong" + color.END)
     
       return 0



def display_score(correct_guesses, guesses):
   print(" ")
   print(color.BOLD+ color.BLUE + "RESULTS"+ color.END)
   print(" ")


   print("Answers: ", end="")
   for i in questions:
       print(questions.get(i), end=" ")
   print()


   print("\nGuesses: ", end="")
   for i in guesses:
       print(i, end=" ")
   print()


   score = int((correct_guesses/len(questions))*100)
   print("\nYour score is: "+str(score)+"% out of 100%")



def play_again():


   response = input("\nDo you want to play again? (yes or no): ")
   response = response.upper()


   if response == "YES":
       return True
   else:
       return False



questions = {
"1. From which continent did the ancestors of the Aboriginal people migrate?:\n ": "B",
"2. After the war, Canada became a more flexible and open society. What was the foundation?:\n  ": "D",
"3. The deportation of the Acadians is also known as:\n  ": "B",
"4. For how long was the title of (Dominion of Canada) officially used?:\n  ": "D",
"5. The Pacific War ends with:\n  ": "A",
"6. What is the meaning of the Remembrance Day?:\n  ": "B",
"7. Who are the Aboriginal peoples of Canada?: \n  ": "C",
"8. Who are the founding peoples of Canada?:\n  ": "B",
"9. What was remarkable about the Canadian navy at the end of the second world war?:\n ": "B",
"10. Which of the following best describes the War of 1812?:\n  ": "D",




"11. A Member of Parliament from Montreal announces that she will spend her weekend in her electoral district. This means she would be:\n  ": "C",
"12. After a federal election, which party forms the new government?\n : ": "A",
"13. Approximately how many Canadians served in the First World War?:\n  ": "D",
"14. Canada has three territories and how many provinces?:\n  " : "B",
"15. Fatima is a new immigrant in Canada. What law allows her to take a job at par with a man?:\n  ": "A",
"16. From where does the name “Canada” come from?:\n  ": "D",
"17. Give an example of how you can show responsibility by participating in your community.?:\n  ": "D",
"18. Give an example of where English and French have equal status in Canada:\n  ": "C",
"19. Give the first line of Canada’s national anthem?:\n  ": "A",
"20. How are Members of Parliament chosen?:\n  ": "B",
}


options = [["A. From America", "B. From Asia", "C. From Australia", "D. From Europe"],
         ["A. Women's inequality", "B. Men's equality", "C. Inequality between men and women", "D. Equality between men and women"],
         ["A. Le Grand Départ ", "B. The Great Upheaval ", "C. The Great Deportation", "D. The Great Disarray "],
         ["A. 250 years", "B. 200 years", "C. 50 years", "D. 100 years"],
         ["A. the surrender of Japan", "B. the surrender of Canada", "C. the surrender of Germany", "D. the victory of Japan"],
         ["A. Remember our sovereign, Queen Elizabeth II", "B. Remember the sacrifice of the Canadians who served or died in the war", "C. Honoring the Prime Ministers who have passed away", "D. Celebrate Confederation"],
         ["A. Descendants of early Australian immigrants to Canada", "B. The first European immigrants to arrive in Canada", "C. The first peoples who lived in Canada", "D. The first settlers in Newfoundland"],
         ["A. Inuit, Aboriginals and British.", "B. Aboriginals, French and British", "C. Aboriginal, Métis and British", "D. The Métis, the French and the British"],
         ["A. It was the fourth navy in the world", "B. It was the third largest marine in the world", "C. It was the largest marine in the world", "D. It was the second largest marine in the world"],
         ["A. Napoleon's fleet was defeated by the Royal Navy", "B. The United States gained independence from the British Empire as a result of this war", "C. Canada joined the United States as a result of this war", "D. The United States invaded Canada and was defeated, allowing Canada to maintain its independence from that country"],
        


         ["A. In her office on Parliament Hill", "B. 1991", "C. In the part of Montreal where she was elected", "D. Going on a vacation"],
         ["A. The party with the most elected representatives is invited by the Governor General to become the party in power ", "B. The King himself picks any party to run the government", "C. The Governor General proposes a law for elected officials to become the governing body", "D. The Premiers of each province pick a party to run the government"],
         ["A. 7000", "B. 8 million", "C. About 60,000", "D. More than 600,000"],
         ["A. 13", "B. 10 ", "C. 3", "D. 5"],
         ["A. Equality of women and men ", "B. Equality of all races", "C. Equal pay for equal work", "D. Equal rights"],
         ["A. From the Inuit word meaning country", "B. From the French word meaning joining", "C. From the Métis word meaning rivers", "D. From Kanata, the Huron-Iroquois word for village"],
         ["A. Mind your own business", "B. Have a party", "C. Keep your property tidy", "D. Volunteer"],
         ["A. In schools", "B. In the workplace", "C. In the Parliament of Canada", "D. At City Hall"],
         ["A. O Canada! Our home and native land! ", "B. O Canada! Our province and native land! ", "C. O Canada! From far and wide, O Canada, ", "D. O Canada! We stand on guard for thee"],
         ["A. Appointed by the Prime Minister","B. Elected by Canadian citizens", "C. Appointed by the King", "D. Elected by the Provincial Ministers"]]


new_game()


while play_again():
   new_game()





print(color.BLUE +"________________________________________________________"+color.END)
print(color.BOLD + color.UNDERLINE + color.BLUE+"THANK YOU FOR TESTING YOUR KNOWLEDGE... UNTIL NEXT TIME!\n"+color.END)


img1= mpimg.imread('canadian-history.jpg')
plt.imshow(img1)